[2024-07-10 13:57:31,700] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-10T13:57:31.193770+00:00 [queued]>
[2024-07-10 13:57:31,710] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-10T13:57:31.193770+00:00 [queued]>
[2024-07-10 13:57:31,710] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 13:57:31,711] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-07-10 13:57:31,711] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-07-10 13:57:31,726] {taskinstance.py:1377} INFO - Executing <Task(DockerOperator): create_seeds> on 2024-07-10 13:57:31.193770+00:00
[2024-07-10 13:57:31,730] {standard_task_runner.py:52} INFO - Started process 841 to run task
[2024-07-10 13:57:31,733] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_layers_in_snowflake', 'create_seeds', 'manual__2024-07-10T13:57:31.193770+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/create_layers.py', '--cfg-path', '/tmp/tmpc7jl8pu8', '--error-file', '/tmp/tmpyk_0fq4j']
[2024-07-10 13:57:31,734] {standard_task_runner.py:80} INFO - Job 14: Subtask create_seeds
[2024-07-10 13:57:31,788] {task_command.py:369} INFO - Running <TaskInstance: create_layers_in_snowflake.create_seeds manual__2024-07-10T13:57:31.193770+00:00 [running]> on host bc9f9d1e47b7
[2024-07-10 13:57:31,865] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_layers_in_snowflake
AIRFLOW_CTX_TASK_ID=create_seeds
AIRFLOW_CTX_EXECUTION_DATE=2024-07-10T13:57:31.193770+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-10T13:57:31.193770+00:00
[2024-07-10 13:57:31,894] {docker.py:247} INFO - Starting docker container from image custom_dbt_image
[2024-07-10 13:57:34,010] {docker.py:308} INFO - [0m13:57:34  Running with dbt=1.5.0
[2024-07-10 13:57:34,011] {docker.py:308} INFO - [0m13:57:34  dbt version: 1.5.0
[2024-07-10 13:57:34,012] {docker.py:308} INFO - [0m13:57:34  python version: 3.7.3
[2024-07-10 13:57:34,013] {docker.py:308} INFO - [0m13:57:34  python path: /usr/bin/python3
[2024-07-10 13:57:34,014] {docker.py:308} INFO - [0m13:57:34  os info: Linux-6.6.31-linuxkit-x86_64-with-debian-10.13
[2024-07-10 13:57:34,014] {docker.py:308} INFO - [0m13:57:34  Using profiles.yml file at /usr/app/dbtlearn/profiles.yml
[2024-07-10 13:57:34,015] {docker.py:308} INFO - [0m13:57:34  Using dbt_project.yml file at /usr/app/dbtlearn/dbt_project.yml
[2024-07-10 13:57:34,015] {docker.py:308} INFO - [0m13:57:34  Configuration:
[2024-07-10 13:57:34,243] {docker.py:308} INFO - [0m13:57:34    profiles.yml file [[32mOK found and valid[0m]
[2024-07-10 13:57:34,275] {docker.py:308} INFO - [0m13:57:34    dbt_project.yml file [[32mOK found and valid[0m]
[2024-07-10 13:57:34,276] {docker.py:308} INFO - [0m13:57:34  Required dependencies:
[2024-07-10 13:57:34,285] {docker.py:308} INFO - [0m13:57:34   - git [[32mOK found[0m]
[2024-07-10 13:57:34,286] {docker.py:308} INFO - [0m13:57:34  Connection:
[2024-07-10 13:57:34,287] {docker.py:308} INFO - [0m13:57:34    account: tsb24868.us-east-1
[2024-07-10 13:57:34,288] {docker.py:308} INFO - [0m13:57:34    user: dbt
[2024-07-10 13:57:34,288] {docker.py:308} INFO - [0m13:57:34    database: AIRBNB
[2024-07-10 13:57:34,289] {docker.py:308} INFO - [0m13:57:34    schema: DEV
[2024-07-10 13:57:34,290] {docker.py:308} INFO - [0m13:57:34    warehouse: COMPUTE_WH
[2024-07-10 13:57:34,290] {docker.py:308} INFO - [0m13:57:34    role: transform
[2024-07-10 13:57:34,291] {docker.py:308} INFO - [0m13:57:34    client_session_keep_alive: False
[2024-07-10 13:57:34,291] {docker.py:308} INFO - [0m13:57:34    query_tag: None
[2024-07-10 13:57:35,493] {docker.py:308} INFO - [0m13:57:35    Connection test: [[32mOK connection ok[0m]
[2024-07-10 13:57:35,493] {docker.py:308} INFO - [0m13:57:35  [32mAll checks passed![0m
[2024-07-10 13:57:35,921] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=create_layers_in_snowflake, task_id=create_seeds, execution_date=20240710T135731, start_date=20240710T135731, end_date=20240710T135735
[2024-07-10 13:57:35,972] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-07-10 13:57:36,014] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
